services:
  airflow:
    container_name: airflow_pollen
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW_HOME=/app/airflow_home
      - AIRFLOW__CORE__DAGS_FOLDER=/app/airflow_pollen/dags  
      - PYTHONPATH=/app:$PYTHONPATH  
    depends_on:
      - postgres

  postgres:
    container_name: postgres_airflow
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin_dagster:
    image: dpage/pgadmin4
    container_name: pgadmin_airflow
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  pg_data:
